version: '3.8'

services:
  mysql:
    image: mysql:9.1.0
    environment:
      MYSQL_DATABASE: musicApp
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306' # Change 3306 on the container to 3307 on the host
